spring.application.name=sys_api_restaurant
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurante_db
spring.datasource.username=restaurante_user
spring.datasource.password=restaurante_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=wXpN8sT2rK5vB7yA3dF6gH9jM4qR0uV1cE8xL5nP2oW6tZ3yC7bI9mA0vS4dG
jwt.expiration=86400000
